#!/bin/bash

FIND=/usr/bin/find
GZIP=/bin/gzip
TAR=/bin/tar
ZIP=/usr/bin/zip

# EXIT STATUSES: http://www.freebsd.org/cgi/man.cgi?query=sysexits&sektion=3
ALL_GOOD=0
EX_USAGE=64
EX_DATAERR=65
EX_NOINPUT=66
EX_NOUSER=67
EX_NOHOST=68
EX_UNAVAILABLE=69
EX_SOFTWARE=70
EX_OSERR=71
EX_OSFILE=72
EX_CANTCREAT=73
EX_IOERR=74
EX_TEMPFAIL=75
EX_PROTOCOL=76
EX_NOPERM=77
EX_CONFIG=78

(exit $ALL_GOOD)
